const CANVAS_WIDTH = 900;
const CANVAS_HEIGHT = 600;
const WALL_TOP = 60;
const WALL_SIDE = 60;
const DOOR_WIDTH = 50;
const DOOR_DEPTH = 60;

export { CANVAS_WIDTH, CANVAS_HEIGHT, WALL_TOP, WALL_SIDE, DOOR_WIDTH, DOOR_DEPTH };
